### ISSUE TITLE
Error in async processData(data)

### ISSUE THREAD

**Issue by IDK-TERADA** [bitfocus/companion-module-idk-ninjar#3]
It seems that an error is occurring in the processing after receiving the command. The error message is as follows:
----------------------------------------------------------------------------------------------------------------------------
error: C:\companion-module-dev\companion-module-dev\companion-module-idk-ninjar-main\src\api.js:92
				self.DATA.outputs[`${videoChannel}`].currentVideoInput = input
				          ^

TypeError: Cannot read properties of undefined (reading 'outputs')
    at ninjarInstance.processData (C:\companion-module-dev\companion-module-dev\companion-module-idk-ninjar-main\src\api.js:92:15)
    at TCPHelper.<anonymous> (C:\companion-module-dev\companion-module-dev\companion-module-idk-ninjar-main\src\api.js:34:10)
    at TCPHelper.emit (C:\companion-module-dev\companion-module-dev\companion-module-idk-ninjar-main\node_modules\eventemitter3\index.js:181:35)
    at Socket.<anonymous> (C:\companion-module-dev\companion-module-dev\companion-module-idk-ninjar-main\node_modules\@companion-module\base\dist\helpers\tcp.js:79:48)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v18.20.4
----------------------------------------------------------------------------------------------------------------------------

If you need any further information, please feel free to comment.

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-idk-ninjar/commit/e972ee55701d0af1f6aab49b1b02cbde05bc91df

This commit adds a default DATA obj, if you want to pull the latest code and try it. (Updated `constants.js` file)
